comments_array = ['Nice',
                  'Keep it Up',
                  'Cool!',
                  '😁😁😁😁',
                  '😆😆😆😆😆😆😆',
                  '😂',
                  '😂😂😂😂😂😂',
                  'Such a Wow 😂😂😂',
                  'i Like it 😕😕',
                  'Follow me Please :/',
                  'So Coooooooooooool :/',
                  'Where is Ma Cat :/',
                  'bot Made by @IM_API',
                  'Weeds Over here 😂😂😂😂',
                  'Fuck Yeah :/',
                  'Are You Sure? :/',
                  'IDK :|',
                  'This is me , Who are you? : --- |',
                  'i believe i can fly 😂😂😂😂😂😂',
                  'Super fun :/',
                  'are you vegan? :/',
                  'im sure your vegan :/',
                  'Yeah 100% your vegan :/',
                  ]
